### ISSUE TITLE
Run UPM Git Extension with Compiler Errors In Unity

### ISSUE THREAD

**Issue by TCROC** [mob-sakai/UpmGitExtension#103]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

Currently, the UPM Git extension only works when there aren't compiler errors.  This is problematic when updating packages that are dependent on each other.

**Describe the solution you'd like**
It would be nice if the UPM Git extension would run even if there are compiler errors in Unity.

**Describe alternatives you've considered**
Currently I have to update the tags in the manifest by hand.

**Comment by mob-sakai** [comment]
Thank you for your reporting!
I would like to know more about this issue.

**Comment by TCROC** [comment]
Currently, if there are any compiler errors, this extension will not run.  For example, maybe I am creating a project and missing some required packages.  The easiest way to install those packages is via this extensions, but this extension won't work if Unity is throwing compiler errors.

Or another example is when I update a package.  Sometimes compiler errors will throw and then I can't downgrade because this extension won't run when there are compiler errors.

**Comment by TCROC** [comment]
Does that make sense?  I'll try to throw together an example project.

**Comment by mob-sakai** [comment]
Sorry for my late reply.
Please try to use `2.0.0-preview.1` 👍
