### ISSUE TITLE
sub dir not working

### ISSUE THREAD

**Issue by hannesdelbeke** [mob-sakai/UpmGitExtension#108]
**Describe the bug**
Sub directory not working when trying to use through tool
Sub directory working when using manually by appending "?path=/SUB_DIRECTORY_NAME" to the giturl in the manifest

**To Reproduce**
1. Go to package manager with UPM git extension installed
2. Click on the red icon top left to add new git package
3. Add repo URL and subfolder
4. version in subfolder doesnt show up

**Expected behavior**
version to correctly show up for packages in a subfolder

**Screenshots**
/

**Environment (please complete the following information):**
 - Version UPM git extension 1.3.4
 - Platform: Editor Windows
 - Unity version: 2019.3.14f1
 - Build options: /

**Additional context**
tested with a fork of this repo
version updates to the json show up correctly in unity when pushed in root folder
when moving whole project to a subfolder any version updates in that subfolder do not show

when looking at the stdout that is printed by the console.log in get-available-versions.js we see

**redacted output from unity**
the package added manually in the manifest using /path correctly shows subfolder
subDir is correctly passed to get-available-versions.js
[manual.txt](https://github.com/mob-sakai/UpmGitExtension/files/5832159/manual.txt)

when trying to add a package from git through this extension using subfolder
subDir is not passed to get-available-versions.js
[gitextension.txt](https://github.com/mob-sakai/UpmGitExtension/files/5832166/gitextension.txt)

**Comment by hannesdelbeke** [comment]
above formatting is broken for the logs, not sure how to fix that

**Comment by hannesdelbeke** [comment]
when manually adding to the manifest, i can access the subdir
1.3.6 is latest commit and in the subdir
note that the dropdown with any previous versions is gone
![image](https://user-images.githubusercontent.com/3758308/104968302-5a25c000-59dd-11eb-8a5f-55846934a424.png)

![image](https://user-images.githubusercontent.com/3758308/104968480-e0420680-59dd-11eb-8bc9-766c88580259.png)

**Comment by hannesdelbeke** [comment]
but when trying to the package using this extension, only the versions in the rootfolder show up
it seems to ignore what i put in the sub-directory field and always show the same versions
![image](https://user-images.githubusercontent.com/3758308/104968768-b0dfc980-59de-11eb-9e87-859066cbba7c.png)

1.3.5 is a test version i added in the root folder
this shows up correctly

1.3.6 is a test version i added in the sub directory
this does not show up

**Comment by mob-sakai** [comment]
@hannesdelbeke 
Thank you for your reporting!
