### ISSUE TITLE
Why all the node.js hassle?

### ISSUE THREAD

**Issue by 0xDEADBAAD-games** [mob-sakai/UpmGitExtension#109]
I was trying to see why the plugin wouldn't list all the tags in my gitlab repo and I stumbled upon the arcane magic it does to communicate with git so I was wondering why this was the chosen solution when you can launch the git exe just like you launch the node console.

I'm planning to migrate that to C# (after which I'll be happy to share the implementation) but I wanted to ask first because maybe there's something I don't know about the way you're supposed to this kind of stuff inside the editor.

**Comment by mob-sakai** [comment]
Sorry for my late reply.

* Supports asynchronous processing
* json-friendly
* Small distribution file size

I think you are right, it could be implemented as a dotnet application.
