### ISSUE TITLE
Nothing visible in the package manager in 2020 after import

### ISSUE THREAD

**Issue by iiidefektiii** [mob-sakai/UpmGitExtension#112]
I imported its in the project 2020.1.12

i dont get the icon to use to import from the git repo. its still just the + and drop arrow in the package manager.

Does this not work in 2020? Am I missing something?

**Comment by iiidefektiii** [comment]
I was able to get this to show up. Initially it does not show up in Unity 2020.1.12. But when I did a change to Android it appeared and stayed active.

**Comment by MatheusMoura17** [comment]
Same problem in 2020.1.2f1

![image](https://user-images.githubusercontent.com/6765023/121427820-866db900-c94b-11eb-9696-54bb0f17b867.png)

**Comment by mob-sakai** [comment]
Sorry for my late reply.
Please try to use `2.0.0-preview.1` 👍

**Comment by MatheusMoura17** [comment]
`2.0.0-preview.1`  works fine!
