### ISSUE TITLE
UpmGitExtension doesn't appear or works in 2021.1+ versions

### ISSUE THREAD

**Issue by john-rosa-playkids** [mob-sakai/UpmGitExtension#113]
UpmGitExtension works fine on the latest version of 2020.3.3f1 and above, but something on unity has changed on the 2021.1 versions and beyond and UpmGitExtensions simply don't show up on them. I don't know for sure how much work is required to make it compatible but seems just an API update requirement with #ifdef UNITY_2021_OR_ABOVE.

**Comment by 2kCarlos** [comment]
Awww... dang.

Yeah, it doesn't seem to have changed the Package Manager UI at all for me on Unity 2021.1.0f1.
Upon installing the UPM Git Extension (version 1.3.4) from Git URL, I got this in the Unity Console (even after a restart):

```
System.NullReferenceException: Object reference not set to an instance of an object
  at Coffee.CSharpCompilerSettings.ReflectionExtensions.Call (System.Object self, System.String methodName, System.Object[] args) [0x0003e] in <64ac538fcfe94cc8acaaea1c65f42fdf>:0 
  at Coffee.CSharpCompilerSettings.Utils.RequestCompilation (System.String assemblyName) [0x0007c] in <64ac538fcfe94cc8acaaea1c65f42fdf>:0 
  at Coffee.CSharpCompilerSettings.Core.DirtyScriptsIfNeeded () [0x00059] in <64ac538fcfe94cc8acaaea1c65f42fdf>:0 
  at Coffee.CSharpCompilerSettings.Core..cctor () [0x0027f] in <64ac538fcfe94cc8acaaea1c65f42fdf>:0 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])
```

**Comment by nauroman** [comment]
Doesn't work with Unity 2021.1.4f1

`System.NullReferenceException: Object reference not set to an instance of an object
  at Coffee.CSharpCompilerSettings.ReflectionExtensions.Call (System.Object self, System.String methodName, System.Object[] args) [0x0003e] in <64ac538fcfe94cc8acaaea1c65f42fdf>:0 
  at Coffee.CSharpCompilerSettings.Utils.RequestCompilation (System.String assemblyName) [0x0007c] in <64ac538fcfe94cc8acaaea1c65f42fdf>:0 
  at Coffee.CSharpCompilerSettings.Core.DirtyScriptsIfNeeded () [0x00063] in <64ac538fcfe94cc8acaaea1c65f42fdf>:0 
  at Coffee.CSharpCompilerSettings.Core..cctor () [0x0027f] in <64ac538fcfe94cc8acaaea1c65f42fdf>:0 
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])`

**Comment by BruceKristelijn** [comment]
This issue is still a thing. I would like to take a shot to solve it but it seems to come from a dll so I am not sure what the best approach is.

**Comment by jason-yak** [comment]
Yup still an issue in 2021.1.10, would love to contribute. Cool project, but yea can't seem to help on this one. Hoping a fix comes along soon so I can try this out.

**Comment by john-rosa-playkids** [comment]
Seems the author is out of reach. @mob-sakai there is something we can help or do you have any statement about the future of this project?

**Comment by Blackclaws** [comment]
The reason as far as I am able to glean from lookign through the project code is that it uses OpenSesame a different project by the same author which modifies the CSharp Compiler in Unity to allow access to Unity Internals which are being modified by this package. OpenSesame is NOT compatible right now with 2021 versions as they have significantly changed the compilation process it seems:

https://github.com/mob-sakai/CSharpCompilerSettingsForUnity/issues/11

**Comment by bassmit** [comment]
Guys the extensions are not needed in latest lts and beyond

**Comment by Blackclaws** [comment]
How is it not needed? The package manager in 2021 only allows adding of git urls, not a lookup of versions or anything similar. Also does 2021 autoresolve git dependencies of git repos? I thought it didn't

**Comment by GeorgeGkas** [comment]
@Blackclaws you're right, the current LTS version (2021) does not automatically resolve, git dependencies of git packages. If I host a package in git and use other git packages as dependencies, the package manager will throw `Cannot perform upm operation: Unable to add package` error. This tool is crucial for small projects and teams.

**Comment by john-rosa-playkids** [comment]
Since I migrated to use direct URLs inside our projects, I will close this issue, but the problem still persists for future users of this package.

**Comment by Blackclaws** [comment]
@john-rosa-playkids Please reopen this issue. As you said it exists still and is NOT fixed.
