### ISSUE TITLE
SemVersion is an ambiguous reference in 2019.4.32

### ISSUE THREAD

**Issue by Zoranner** [mob-sakai/UpmGitExtension#117]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
```bash
Library\PackageCache\com.coffee.upm-git-extension@7a00a38eb8\Editor\Coffee.UpmGitExtension\Extensions\UpmPackageVersionEx.cs(22,24): error CS0104: 'SemVersion' is an ambiguous reference between 'UnityEditor.Scripting.ScriptCompilation.SemVersion' and 'UnityEditor.PackageManager.UI.SemVersion'
```

**Environment (please complete the following information):**
 - Version [2.0.0-preview.1]
 - Platform: [Editor(Windows)]
 - Unity version: [2019.4.32]

**Comment by mob-sakai** [comment]
UpmGitExtensions v2 is not available in Unity2018 or 2019.
Please use `v1` instead.

**Comment by mob-sakai** [comment]
For details, see https://github.com/mob-sakai/UpmGitExtension/tree/develop#installation-for-unity-2018-or-2019
