### ISSUE TITLE
Newer packages version not updating unless restarting editor

### ISSUE THREAD

**Issue by Svartskogen** [mob-sakai/UpmGitExtension#121]
**Describe the bug**
I'm consistently experiencing that the Package Manager windows is not retrieving/fetching new versions of the packages I'm using.
I found that I can only see new versions when I exit the Unity editor and open again. 
I tried clearing the cache, closing the Package Manager window, refreshing, resolving and every combination of the after-mentioned.

**To Reproduce**

1. Using a personal package hosted on GitLab/GitHub
2. While I have the Editor open on a project with my package, I push an update to my package repo's
3. I dont see the new version on the Package Manager in the project that is using the Package, even after refreshing, resolving, clearing cache, etc.
4. If I exit the editor and open it again, without doing anything else, I can see in the Package Manager windows that my package has a new Version

**Expected behavior**
To see the new update after pushing it and refreshing on the Editor.

**Environment (please complete the following information):**
 - Version `2.0.0-preview.4`
 - Platform: Android, Win Standalone
 - Unity version: `Unity 2021.1.28f1`

**Comment by mob-sakai** [comment]
Thank you for your reporting! :+1: 
To prevent excessive network load, each git repository update has a 5-minute cool time.
However, I think it should force them to update when the user presses the refresh button.

**Comment by Svartskogen** [comment]
fixed on version 2.0.0-preview.5
