### ISSUE TITLE
Repo versions not listed

### ISSUE THREAD

**Issue by TellmewowBilbao** [mob-sakai/UpmGitExtension#122]
I'm not able to list release versions of my private repo after clicking "Find Versions".
Probably I'm missing some files or config in my Github repo, I only added package.json in the root directory (not sure if this is mandatory).
![UPM](https://user-images.githubusercontent.com/96303148/171855081-bef0e6fe-2c43-4fbb-9c7e-69dc5a95fb14.png)

**Comment by mob-sakai** [comment]
`package.json.meta` is required.
https://github.com/mob-sakai/UpmGitExtension/blob/preview/Editor/Commands/fetch-packages.js#L53
