### ISSUE TITLE
Installation of provided Samples folder is not working unless the editor is restarted

### ISSUE THREAD

**Issue by ZeynelKoca** [mob-sakai/UpmGitExtension#123]
**Describe the bug**
After installing a package, trying to install the included samples results in an error: `[Package Manager] Cannot import sample Prefabs: The path C:/Users/USER/Desktop/Projects/PackageImportTest/Library/PackageCache/com.company.package@2df65ed0cf/Samples~/Prefabs does not exist.
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)`.

Restarting the Unity project fixes this problem. Bug might be related to the problem described in #121 

**To Reproduce**
1. Install a package through the UpmGitExtension panel using the SSH protocol
2. The package installs as expected and appears in the Package Manager window
3. Click on 'Samples' dropdown, which is provided with the installed package
4. Click on 'Import' on any of the provided samples.
5. See error message in issue description

**Expected behavior**
Proper installation of the samples, without the need of restarting the editor.

**Environment (please complete the following information):**
 - Version 2.0.0-preview.5
 - Platform: Windows
 - Unity version: 2021.3.2f1
 - Build options: Not relevant

**Comment by mob-sakai** [comment]
Thank you for your reporting!

**Comment by ZeynelKoca** [comment]
Somehow I haven't been able to reproduce this bug as of today. Feel free to close the issue if it's the same case for you.

If I happen to reproduce it again, I'll try to find more details as to what exactly caused the bug to reappear.

**Comment by mob-sakai** [comment]
The issue is not reproduced on my environment.
 If the same issue arises, please re-open this issue. 👍
