### ISSUE TITLE
error on Unity2022.2.0a

### ISSUE THREAD

**Issue by chaoslife** [mob-sakai/UpmGitExtension#124]
upmPackage doesn't exist UpdateVersions

Library\PackageCache\com.coffee.upm-git-extension@8b872a6987\Editor\Coffee.UpmGitExtension\GitPackageDataBase.cs(244,36): error CS1061: 'UpmPackage' does not contain a definition for 'UpdateVersions' and no accessible extension method 'UpdateVersions' accepting a first argument of type 'UpmPackage' could be found (are you missing a using directive or an assembly reference?)

**Comment by mob-sakai** [comment]
Thank you for your reporting!
