### ISSUE TITLE
Unity2021.3.21 Error

### ISSUE THREAD

**Issue by chaoslife** [mob-sakai/UpmGitExtension#126]
![image](https://user-images.githubusercontent.com/2386021/198768228-35836fe9-81d3-46ca-bacd-b5b05b3c23ea.png)

In unity2021.3.21, it lost packageInfo

**Comment by haaanz** [comment]
I have this issue too,  Unity 2021.3.12f1

**Comment by enpiech** [comment]
I have this too, Unity 2021.3.12f1

**Comment by SixParQuatre** [comment]
Still happening in 2021.3.13f1. 

As a note to peeps watching this: it looks like PackageManager changed pretty significantly again (in an LTS of all places _sigh_).
I tried to do a local hack/fix and managed to get rid of the compile errors; even got the installation of new packages to work partially (seems to work with some repo, but not all) but couldn't get the update workflow to work properly - which is arguably the most important useful part.

Here's hoping @mob-sakai has got a solution in the pipe; and that it's not too much  of a headache. :)

**Comment by SixParQuatre** [comment]
For anybody interested, I've made a few changes and got the update to work... somehow. 
The button shows all the time, but if a version is indeed available it will grab.
There's still a huge amount of guesswork in what I've done, it's a lot of plugging holes without having a deep understanding of the whole... but here's  a patch file you can apply on main to get where I got to and maybe continue.
Note: I add to put the .diff file in a zip because it wouldn't allow me to attach it.
[patch.zip](https://github.com/mob-sakai/UpmGitExtension/files/10073402/patch.zip)

**Comment by ess4654** [comment]
Your diff file does not work I keep getting this same problem.

\
ArgumentNullException: Value cannot be null.
Parameter name: source
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <109e781b32ec464d8737a667de805742>:0)
UnityEditor.PackageManager.UI.Internal.UpmPackageVersion.get_hasEntitlementsError () (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.Internal.BasePackage+<>c.<get_hasEntitlementsError>b__17_1 (UnityEditor.PackageManager.UI.Internal.IPackageVersion version) (at <37f37e0608764fbd9fb36c76311e810e>:0)
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <109e781b32ec464d8737a667de805742>:0)
UnityEditor.PackageManager.UI.Internal.BasePackage.get_hasEntitlementsError () (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.Internal.PageManager+<>c.<Refresh>b__94_0 (UnityEditor.PackageManager.UI.Internal.IPackage package) (at <37f37e0608764fbd9fb36c76311e810e>:0)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].MoveNext () (at <109e781b32ec464d8737a667de805742>:0)
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <109e781b32ec464d8737a667de805742>:0)
UnityEditor.PackageManager.UI.Internal.PageManager.Refresh (UnityEditor.PackageManager.UI.Internal.RefreshOptions options, System.Int32 pageSize) (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.Internal.PageManager.Refresh (System.Nullable`1[T] tab, System.Int32 pageSize) (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.Internal.PackageManagerWindowRoot.DelayRefresh (UnityEditor.PackageManager.UI.Internal.PackageFilterTab tab, System.String subPage) (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.Internal.PackageManagerWindowRoot.CreateGUI () (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.PackageManagerWindow.CreateGUI () (at <37f37e0608764fbd9fb36c76311e810e>:0)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d6232873609549b8a045fa15811a5bd3>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <d6232873609549b8a045fa15811a5bd3>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <d6232873609549b8a045fa15811a5bd3>:0)
UnityEditor.UIElements.DefaultEditorWindowBackend.Invoke (System.String methodName) (at <71490f95a19640fc8659d65903937f08>:0)
UnityEditor.UIElements.DefaultEditorWindowBackend.SendInitializeIfNecessary (System.Boolean duringOnCreate) (at <71490f95a19640fc8659d65903937f08>:0)
UnityEditor.UIElements.DefaultEditorWindowBackend.RegisterWindow (System.Boolean duringOnCreate) (at <71490f95a19640fc8659d65903937f08>:0)
UnityEditor.UIElements.DefaultEditorWindowBackend.UnityEditor.IEditorWindowBackend.OnRegisterWindow () (at <71490f95a19640fc8659d65903937f08>:0)
UnityEditor.HostView.RegisterSelectedPane (System.Boolean sendEvents) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.HostView.SetActualViewInternal (UnityEditor.EditorWindow value, System.Boolean sendEvents) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.DockArea.SetSelectedPrivate (System.Int32 value, System.Boolean sendEvents) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.DockArea.AddTab (System.Int32 idx, UnityEditor.EditorWindow pane, System.Boolean sendPaneEvents) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.DockArea.AddTab (UnityEditor.EditorWindow pane, System.Boolean sendPaneEvents) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.EditorWindow.CreateNewWindowForEditorWindow (UnityEditor.EditorWindow window, System.Boolean loadPosition, System.Boolean showImmediately, System.Boolean setFocus) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.EditorWindow.Show (System.Boolean immediateDisplay) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.EditorWindow.Show () (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.EditorWindow.GetWindowPrivate (System.Type t, System.Boolean utility, System.String title, System.Boolean focus) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.EditorWindow.GetWindow (System.Type t, System.Boolean utility, System.String title, System.Boolean focus) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.EditorWindow.GetWindow[T] (System.Boolean utility, System.String title, System.Boolean focus) (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.EditorWindow.GetWindow[T] () (at <6a5b55f2e18b419e9faedac06ac6af94>:0)
UnityEditor.PackageManager.UI.PackageManagerWindow.SelectPackageAndFilterStatic (System.String packageToSelect, System.Nullable`1[T] filterTab, System.Boolean refresh, System.String searchText) (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.PackageManagerWindow.OpenPackageManager (System.String packageToSelect) (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.Window.Open (System.String packageToSelect) (at <37f37e0608764fbd9fb36c76311e810e>:0)
UnityEditor.PackageManager.UI.Window.ShowPackageManagerWindow (UnityEditor.MenuCommand item) (at <37f37e0608764fbd9fb36c76311e810e>:0)

**Comment by SixParQuatre** [comment]
Sorry, I can't repo this error on my end (2021.3.14f1 on windows) and ith my current understanding of the packagemanager and this package, I can't get any info out of this callstack.
Like I mentioned the changes I did are a 'best guess' so I can't guarantee universal success.
Sorry that it didn't work for you :/

**Comment by GID0317** [comment]
![206834430-c9470432-13cd-4a94-9d92-09586918bc4a](https://user-images.githubusercontent.com/108791227/207031624-38d93afd-1ffc-4373-b131-394060ba1284.png)

Before i upgrade my unity (Unity 2022.1.24) to Unity 2022.2.0f1 the this package still working and after i upgrade to the latest Unity 2022.2.0f1 "package info" error appear

**Comment by GID0317** [comment]
In the unity 2022.1.24 i also encounter this issue but i got it solved by deleting the cache package and reset package to default. But in 2022.2.0f1 its not working again

**Comment by ujell** [comment]
This is also happening in Unity 2020.3.42f1.
