### ISSUE TITLE
Unity 2022.3 compilation error

### ISSUE THREAD

**Issue by bkslasher** [mob-sakai/UpmGitExtension#132]
Using Windows Edtior 2022.3.0f1:

`Library\PackageCache\com.coffee.upm-git-extension@d0c1cbb541\Editor\Coffee.UpmGitExtension\Extensions\UpmPackageVersionEx.cs(54,16): error CS1729: 'UpmPackageVersion' does not contain a constructor that takes 0 arguments`

**Comment by janimator0** [comment]
☝️ Getting the same issue

**Comment by DevinWeidinger** [comment]
@mob-sakai 2023.3 is now LTS, think we can get this resolved?
