### ISSUE TITLE
failed writing pack file

### ISSUE THREAD

**Issue by BarionLP** [mob-sakai/UpmGitExtension#136]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
from time to time the console shows an error the message basically says: cannot write keep file '.git/objects/pack/pack-3a2bd4ea30e1eb27a48e4968cc3d2465f8aa943e.keep': Filename too long
it seems to be related to the multiplayer samples utilities

**To Reproduce**
1. Install https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop.git?path=/Packages/com.unity.multiplayer.samples.coop#main
2. Error should be displayed in the console

**Expected behavior**
everything works even with the error, but it shouldn't happen

**Screenshots**

**Environment (please complete the following information):**
 - Version 2.0.3
 - Platform: Editor(Windows)
 - Unity version: 2023.1.10f1
 - Build options: .Net 4.x

**Additional context**
```
technologies~com.unity.multiplayer.samples.coop@packages~com.unity.multiplayer.samples.coop.json.lock
stderr:
fatal: cannot write keep file '.git/objects/pack/pack-3a2bd4ea30e1eb27a48e4968cc3d2465f8aa943e.keep': Filename too long
fatal: fetch-pack: invalid index-pack output
child_process.js:526
    throw err;
    ^
```

**Comment by mob-sakai** [comment]
Please try following command.
```sh
git config --system core.longpaths true
```
