### ISSUE TITLE
Support GitLab.com

### ISSUE THREAD

**Issue by Lasser01** [mob-sakai/UpmGitExtension#14]
Love the work you are doing, keep it up 👍 
It is possible to add support for GitLab, both private and public repos, that would be cool?

**Comment by mob-sakai** [comment]
Supporting GitLab is an easy task. :)
I will research about support of private repository later.
I think it requires api access token or username/password.

**Comment by Lasser01** [comment]
Sounds good, thanks for the quick reply, good luck :)

**Comment by mob-sakai** [comment]
Unfortunately, gitlab api requests private access token...
(GitHub and Bitbucket apis don't request)

I am looking for another way to get the names of all the branches/tags.
  * libgit2sharp
  * git on command line

**Comment by mob-sakai** [comment]
UPM requests 'executable git' to install a package with git.
If git is not installed, the following error message appears.
```
An error occurred while resolving packages:
  Project has invalid dependencies:
    **********(package name): No 'git' executable was found. Please install Git on your system and restart Unity

A re-import of the project may be required to fix the issue or a manual modification of **********(project path)/Packages/manifest.json file.
```

**Comment by buihuuloc** [comment]
`Unfortunately, gitlab api requests private access token...`

Can we config the private access token somewhere in the editor or in a config file?

**Comment by mob-sakai** [comment]
Hi @buihuuloc 
The problem here is that private access token is also required for the **public** repository on GitLab...

Fortunately, we can get all branch/tag names by running `git ls - remote repo_url` on the command line. :)

**Comment by buihuuloc** [comment]
Is the support custom domain for gitlab?
I have my own in-house gitlab website.

**Comment by mob-sakai** [comment]
@buihuuloc 
I don't have own GitLab server, so I can not test it right away...
How does UpmGitExtension work on GitLab server?
* Document links are incorrect
* Logo is incorrect
* Repo url is incorrect
* Uploading the package version is not available

**Comment by mob-sakai** [comment]
@Lasser01 
About private repository >>> #15
