### ISSUE TITLE
For private repository

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UpmGitExtension#15]

**Comment by mob-sakai** [comment]
0.6.0+ works fine for private repository. :)

To access the private repository without `username:private_access_token` or `username:password`, use `ssh://` scheme and OpenSSH.

For example, add `"com.coffee.private-test": "ssh://git@github.com/mob-sakai/PrivateTest.git#master",` to `Packages/manifest.json`.

**Comment by jeffcampbellmakesgames** [comment]
I've been able to use private repositories on github via an https url where my computer has an SSH key registered with the appropriate github account.
