### ISSUE TITLE
Unable to add package from url on Windows

### ISSUE THREAD

**Issue by vanifatovvlad** [mob-sakai/UpmGitExtension#22]
When I try to add any package from url, for example, https://github.com/mob-sakai/GitPackageTest.git after selecting a branch the following error appears in the logs:
```
Error: git clone --depth=1 --branch 0.5.0
 --single-branch https://github.com/mob-sakai/GitPackageTest.git Temp/UpmGit

Cloning into 'Temp/UpmGit'...
warning: Could not find remote branch 0.5.0? to clone.
fatal: Remote branch 0.5.0? not found in upstream origin
```
This can be fixed by replacing:
```
result.Add (m.Groups [2].Value);
```
To:
```
result.Add (m.Groups [2].Value.Trim());
```
Line 52 Utils.cs (GitUtils.GetRefs)

**Comment by mob-sakai** [comment]
Hi @vanifatovvlad 
Thank you for yor reporting!

**Comment by mob-sakai** [comment]
The issue is reproduced on Windows.
I'll fix it ASAP.
