### ISSUE TITLE
Can you detail how you create the upm subtree branch

### ISSUE THREAD

**Issue by Formic** [mob-sakai/UpmGitExtension#25]
I'm not very familiar with subtrees, and with what I've been reading about them, it's not very clear to me how to properly setup the branch. I was curious if you could add some details to that section for how to best set it up?

Thanks!

**Comment by mob-sakai** [comment]
Hi @Formic 
I will write an article about it later.
Wait a moment!

**Comment by mob-sakai** [comment]
Thank you for waiting. :)
https://www.patreon.com/posts/25070968

**Comment by Formic** [comment]
That was perfect @mob-sakai , thank you so much!
