### ISSUE TITLE
Updatable indicator

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UpmGitExtension#26]
![image](https://user-images.githubusercontent.com/12690315/54483525-dd34d700-4897-11e9-8ee0-1e7935b1247f.png)

**Comment by mob-sakai** [comment]
WIP: I succeeded in displaying any version of a package on Package Manager UI.
![image](https://user-images.githubusercontent.com/12690315/58867995-65d44e00-86f6-11e9-9e39-bd3cd0d215cc.png)

**Comment by RickyIsPrettyRad** [comment]
That is VERY nice!!!
