### ISSUE TITLE
2019.1+ Doesn't show all availible versions

### ISSUE THREAD

**Issue by StephenHodgson** [mob-sakai/UpmGitExtension#28]
![image](https://user-images.githubusercontent.com/13334553/55302376-ba590580-53f5-11e9-8155-07e172d59ef0.png)

The test repo has versions 0.1.0-0.5.0 but it doesn't show up in 2019.1+

Should look like:
![image](https://user-images.githubusercontent.com/13334553/55302402-e2e0ff80-53f5-11e9-92fd-488c96af5c53.png)

**Comment by mob-sakai** [comment]
Hi @StephenHodgson 
It's by design.
In Unity Package Manager UI 2.1.0, you can upgrade the package using the controls at the bottom of the window.

I'm looking for a better way. :)

**Comment by mob-sakai** [comment]
![image](https://user-images.githubusercontent.com/12690315/52464583-d17e3280-2bbe-11e9-83d9-454d100c0dd4.png)

**Comment by mob-sakai** [comment]
WIP: I succeeded in displaying any version of a package on Package Manager UI.
![image](https://user-images.githubusercontent.com/12690315/58867995-65d44e00-86f6-11e9-9e39-bd3cd0d215cc.png)

**Comment by mob-sakai** [comment]
ref #37 
This issue will be resolved soon.
