### ISSUE TITLE
Working with packages that have git dependencies?

### ISSUE THREAD

**Issue by StephenHodgson** [mob-sakai/UpmGitExtension#29]
I was trying to use a [git upm package with other git upm package dependencies](https://forum.unity.com/threads/git-support-on-package-manager.573673/page-2#post-4389751) but ran into some errors.

Have you been able to get this to work @mob-sakai?

**Comment by mob-sakai** [comment]
Hi @StephenHodgson 
No.
I think this feature is necessary for UPM.
I'm trying to implement this in another way.

**Comment by StephenHodgson** [comment]
[I think I figured it out.](https://github.com/XRTK/XRTK-Core/pull/57/files?file-filters%5B%5D=.cs&file-filters%5B%5D=.meta#diff-e853425bb7228b276e205446caa0ea6bR61)

**Comment by mob-sakai** [comment]
Wow!

**Comment by mob-sakai** [comment]
I'm trying to implement the following mechanism.
- Define `gitDependencies` instead of `dependencies` in `package.json` file.
- Clone all `gitDependencies` contained in `Library/PackageCache/*/package.json` files.

**Comment by mob-sakai** [comment]
I tried some ideas this weekend and one of them works well. :)
1. Define `gitDependencies` (sub-packages) in `package.json` contained in the target package
1. Add the target package using UpmGitExtension
1. Recursively collect sub-packages included in gitDependencies
1. Add sub-packages to project's manifest.json
1. Add the target package using Client.Add

**Comment by StephenHodgson** [comment]
Not sure if it's a good idea to add to the `manifest.json` cause Unity might just overwrite our changes. Happened to be before with the assembly definitions in the past.

**Comment by StephenHodgson** [comment]
I ended up going with a scriptable object to hold the data and keep track of the dependencies

**Comment by mob-sakai** [comment]
Oh, sorry.
I missed your commit and made a mistake.
It looks very nice. :)

Can I integrate this mechanism into UpmGitExtensions?

**Comment by mob-sakai** [comment]
Your mechanism is as follows, right?
1. Install `XRTK.Core` in some way
1. `XRTK.UpmGitExtension`, `XRTK.WindowsMixedReality` and `XRTK.SDK` are automatically installed

The dependency graph looks like this:
- `XRTK.SDK`
  -  `XRTK.WindowsMixedReality`
      - `XRTK.Core`
        - `(XRTK.UpmGitExtension)` // The assembly is not depended.

In other words, `XRTK.SDK` is the top of dependencies.
I want to **resolve all dependencies when installing `XRTK.SDK`.**

Do you think this is possible with your mechanism?

**Comment by StephenHodgson** [comment]
I believe so. But it's a bit of a manual setup with having to define them in the scriptable object in the core.

**Comment by StephenHodgson** [comment]
The mechanism can probably be improved though. Any suggestions are welcome!

**Comment by mob-sakai** [comment]
For project with package dependency such as:
```
My Project
├ Someone's PackageA 0.1.0
│ └ Someone's CorePackage1 0.1.0 
└ My PackageB 0.1.1
　 ├ Someone's CorePackage1 0.2.0
　 └ My CorePackage2 0.2.0
```

Finally, the following packages are installed:
```
Someone's PackageA 0.1.0
Someone's CorePackage1 0.2.0 
My PackageB 0.1.1
My CorePackage2 0.2.0
```

* When we install/update/delete packages using UpmGitExtension, reinstall the missing packages.
  * If you removed `Someone's CorePackage1`, reinstall it.
  * If you updated `My CorePackage2` to `0.3.0`, do nothing.
* Depends on **someone's core-package** on GitHub.
  * Therefore, the core-package does not have a script for resolving dependencies.

**Comment by mob-sakai** [comment]
@StephenHodgson 
Do you have any good ideas?

**Comment by RickyIsPrettyRad** [comment]
Hi, this is sounding REALLY interesting. We have some packages that are dependent upon other packages. Your plan is to allow some kind of extra markup - probably in the package.json? Then when using the UPM Git Extension it will check for dependencies and then pull them all into the project in one go?

Some questions :
will the new dependency markup be compatible if someone is NOT using UPM Git Extension? I mean just not causing any errors.
how would you control the case of Package A depends upon Package B.... BUT a team has their own custom Package B... in our use case this is a very real possibility. Worst case it's be good to be asked if we want UPM Git Extension to pull all dependencies (or perhaps present a window with tick boxes next to all dependencies and we can choose which ones to auto pull)?

Overall my concern is there will be many edge cases that will be hard to catch. As long as this is an optional feature I THINK it will be safe...

**Comment by mob-sakai** [comment]
Hi @RickyIsPrettyRad 

**In my plan:**

1. The package developers add `gitDependencies` extra markup in the `package.json`.
2. When you install/update/delete packages using UpmGitExtension, all `gitDependencies` in the `package.json` are collected recursively.
3. Select and install the packages you need.
![image](https://user-images.githubusercontent.com/12690315/56227049-8ea17500-60af-11e9-8818-cc7d8c5ee055.png)
NOTE: This is WIP version

>will the new dependency markup be compatible if someone is NOT using UPM Git Extension? I mean just not causing any errors.

Yes.
The only difference is that `gitDependencies` are ignored.
You can install the package manually.

>how would you control the case of Package A depends upon Package B.... BUT a team has their own custom Package B... in our use case this is a very real possibility.

Ah, I often customize the package, too.
You can select the packages to install. (See above)

**Comment by mob-sakai** [comment]
I know this way is "a stupid way".
This feature should be supported by the official. X(

**Comment by RickyIsPrettyRad** [comment]
PERFECT!
That looks really great! I wonder if Unity will one day implement these features?

**Comment by StephenHodgson** [comment]
Looking good. I will advice against adding custom data to the `package.json` as it's overwritten by unity when using embedded package

**Comment by mob-sakai** [comment]
@StephenHodgson 

>it's overwritten by unity when using embedded package

How can I see the behavior?

**Comment by StephenHodgson** [comment]
1. create an embedded package and then edit the package data using the inspector
![image](https://user-images.githubusercontent.com/13334553/56283786-89e8bb00-60c7-11e9-8b47-8e45fb525c69.png)
2. manually edit the package
3. switch back to the inspector and change a value, then press `apply`
4. switch back to the file and see custom values are gone

**Comment by mob-sakai** [comment]
Thanks!

**Comment by mob-sakai** [comment]
@StephenHodgson 
No problem.
I noticed that the custom values are gone **only if they are empty.**

**The custom value will be kept:**
```
gitDependencies
{
  "com.test.package" : "https://test.package.git"
}
```

**The custom value will be gone:**
```
gitDependencies
{
}
```

**Comment by mob-sakai** [comment]
@StephenHodgson 
In my environment, the custom values will be kept...

[packageJsonTest.zip](https://github.com/mob-sakai/UpmGitExtension/files/3090040/packageJsonTest.zip)
- Unity 2019.1.0f2
- Check `Packages/UPM Git Extension Test (GitLab)/package.json`
```
...
gitDependencies
{
  "com.test.package" : "https://test.package.git"
}
...
```

**Comment by StephenHodgson** [comment]
Interesting. On mine the values get replaced. I tried to do something similar with the asmdef files a while back.

**Comment by StephenHodgson** [comment]
I found a solution that will work for my needs in my fork.

Would you like me to close this issue?

**Comment by mob-sakai** [comment]
Wow, congratulations!
Please tell me before closing.
What kind of solution is that?

**Comment by StephenHodgson** [comment]
https://github.com/mob-sakai/UpmGitExtension/issues/29#issuecomment-480530806

This one, then added them in if the package was missing.

**Comment by mob-sakai** [comment]
@StephenHodgson @RickyIsPrettyRad 
I made a new plugin that resolves git url dependencies in the package for Unity Package Manager.
Try it! :)
https://github.com/mob-sakai/GitDependencyResolverForUnity

**Comment by RickyIsPrettyRad** [comment]
EXCELLENT!
I'll grab this soon
