### ISSUE TITLE
Support .Net 3.5 scripting runtime version

### ISSUE THREAD

**Issue by RickyIsPrettyRad** [mob-sakai/UpmGitExtension#30]
Hi,

Trying out this extension using Unity version 2018.3.10f1. Initially grabbed 0.7.0 (as per docs). Selecting the UPM Git Extension (or one of our own custom packages) in the Package Manager window and we get an error in console at Settings.cs line 34. 

If I downgrade to version 0.6.1 or lower this error goes away and everything seems fine.

Thanks!
Ricky

**Comment by mob-sakai** [comment]
Hi @RickyIsPrettyRad 
Thank you for reporting!

**Comment by mob-sakai** [comment]
@RickyIsPrettyRad

1. I would like to know more information on this issue.
Unity version, platform, more infomation...

2. Upgrade to 0.8.0. Does it work well?

**Comment by mob-sakai** [comment]
Eureka!
This problem occurs when you set `Scripting Runtime Version` to .Net 3.5!
I'll fix it to work with .Net 3.5. :)

**Comment by mob-sakai** [comment]
@RickyIsPrettyRad 
Eureka!
This problem occurs when you set Scripting Runtime Version to .Net 3.5!
I'll fix it to work with .Net 3.5. :)

**Comment by RickyIsPrettyRad** [comment]
Hi,

Sorry I have been away a few days and just returned. I have updated to 0.8.1 in my project and I'm still getting the same error.

To answer your earlier questions : 
Unity 2018.3.10f1
Windows platform
Scripting runtime Version .NET 4.x Equivalent
Scripting Backend Mono
Api Compatibility >NET Standard 2.0

Thanks!

**Comment by mob-sakai** [comment]
Oh, sorry.
I'll try it.

**Comment by mob-sakai** [comment]
Ref: #31

**Comment by mob-sakai** [comment]
@RickyIsPrettyRad 
Please try 0.8.2.

**Comment by RickyIsPrettyRad** [comment]
Looking good! Thank you for the quick fix :)
