### ISSUE TITLE
package manager does show when an update is availible

### ISSUE THREAD

**Issue by StephenHodgson** [mob-sakai/UpmGitExtension#33]
For upm hosted packages it will show an arrow next to the package that has updates.

We might want to add a similar mechanism to notify people there's upstream changes.

![image](https://user-images.githubusercontent.com/13334553/57160714-6f3c6480-6d9e-11e9-9f95-b5d09119f06e.png)

**Comment by mob-sakai** [comment]
Hi @StephenHodgson 

I have an idea about this.
If the version conforms to [SemVer](https://semver.org/) and is equal to the tag name, we can get a list of versions by git command.

`git ls-remote --refs {repo_url}`

If there is a newer version than the installed version, display an arrow.

**Comment by mob-sakai** [comment]
ref #26

**Comment by StephenHodgson** [comment]
I'll close this as it's a duplicate. Sorry :)
