### ISSUE TITLE
Error on 'git ls-remote' for private repos accessed via SSH

### ISSUE THREAD

**Issue by Saruto** [mob-sakai/UpmGitExtension#34]
Hi,
My private repo is only meant to be accessed via an ssh url. Adding the package by URL in the editor works fine, but I get this error whenever I click the package in the editor:

![Screen Shot 2019-05-10 at 11 11 01 AM](https://user-images.githubusercontent.com/6063483/57537542-7fab8c80-7314-11e9-8416-a2a3551d180f.png)

Typing the same command in my terminal yields the same results. However, the command seems to work when I replace "https" with "ssh".

![Screen Shot 2019-05-10 at 11 17 14 AM](https://user-images.githubusercontent.com/6063483/57538310-23496c80-7316-11e9-8eb5-3e09595ec8aa.png)

Is it possible for this command to use ssh when the repo url uses ssh instead of https?

Thanks!

**Comment by mob-sakai** [comment]
Hi  @Saruto 
Oh, it's a bug!
I will fix it asap. :)

**Comment by mob-sakai** [comment]
Hmm, do the following url work well in terminal?
* `ssh://~`
* `ssh://git@~`

**Comment by mob-sakai** [comment]
Please try UpmGitExtension 0.8.3 :)

**Comment by Saruto** [comment]
Just updated, everything seems to work fine!

Thanks for the quick response/fix! :)

**Comment by mob-sakai** [comment]
👍
