### ISSUE TITLE
Support git dependency in the package

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UpmGitExtension#35]
ref #29 
Import from: https://github.com/mob-sakai/GitDependencyResolverForUnity

> This plugin resolves git url dependencies in the package for Unity Package Manager.
You can use a git url as a package dependency as following:
```
[ package-a/package.json ]
{
  "name": "com.coffee.package-a",
  "version": "0.1.0",
  "dependencies": {
    "com.coffee.core-a" : "https://github.com/mob-sakai/GitPackageTest#core-a-0.1.0"
  }
}
```

Please note the risk you are taking when using this package:
https://forum.unity.com/threads/git-support-on-package-manager.573673/page-3#post-4552084

**Comment by mob-sakai** [comment]
To support GitDependencyResolverForUnity, when installing a package, edit `manifest.json` instead of calling `Client.Add` .

https://github.com/mob-sakai/GitDependencyResolverForUnity/issues/18

**Comment by starikcetin** [comment]
Or maybe you could do the resolving via GitDependencyResolver before requesting a package via the API. First, request the dependencies, then request the package itself.

Would that work?

**Comment by mob-sakai** [comment]
Some corrections are needed, but I think it will almost work.

**Comment by mob-sakai** [comment]
When install/update the package with UpmGitExtension...
* Download package.json and check supported unity version
* Resolve git dependencies
* Install/update the package
* (Resolve official dependencies automatically)
