### ISSUE TITLE
A workflow without subtree split

### ISSUE THREAD

**Issue by starikcetin** [mob-sakai/UpmGitExtension#46]
What if we used a config JSON at the root of the repository that contained the path to the `package.json` file, so that we no longer need it to be at the root of the repository?

Then after cloning, we can simply use the folder containing the package.json as the UPM package.

This way we wouldn't need to maintain a separate branch just for UPM releases.

What do you think? Is this feasible, or even possible?

**Comment by mob-sakai** [comment]
Hi @starikcetin 
No, all packages must contain package.json in the root directory.
This is a rule for UPM, not for this plugin.

**Comment by starikcetin** [comment]
So the prettiest option would be maintaining a separate repo just for the UPM releases I suppose. Because the upm branch clutters the main branch hierarchy too much in my opinion.

**Comment by starikcetin** [comment]
Or maybe I can do a feature request to the UPM guys directly, let me see.

**Comment by mob-sakai** [comment]
It would be great if third-party publisher could publish to the official upm registry! :)

**Comment by starikcetin** [comment]
I opened a thread in the unity forums to request this particular feature: https://forum.unity.com/threads/feature-request-support-for-non-root-git-packages.728417/

**Comment by mob-sakai** [comment]
> Because the upm branch clutters the main branch hierarchy too much in my opinion.

What does this mean?

* subtree split doubles tree history
* subtree split/merge generates merge commit

**Comment by starikcetin** [comment]
> > Because the upm branch clutters the main branch hierarchy too much in my opinion.
> 
> What does this mean?
> 
> * subtree split doubles tree history
> * subtree split/merge generates merge commit

The first one mainly. I'm fine with merge commits, but having duplicated history is a maintenance nightmare.

**Comment by mob-sakai** [comment]
Ah, I hate it too!
In this repository, I execute squashed-split every release.
https://github.com/mob-sakai/UpmGitExtension/commits/upm

**Comment by starikcetin** [comment]
Is squashed-split a git script of yours? I manually squash by soft resetting and re-commit. I would have written it myself, but my git scripting is a little rusty.

**Comment by mob-sakai** [comment]
@starikcetin 
I use this:
https://www.npmjs.com/package/git-snapshot

I want a simpler release workflow...
* Changelog: Generate based on commit message, not Github issues.
  * https://github.com/conventional-changelog/conventional-changelog
* Versioning: Automatically, not manually
* Portability: Just execute `npm run release`
* Release: Tag and squashed-split to upm branch and release on Github

**Comment by starikcetin** [comment]
> @starikcetin
> I use this:
> https://www.npmjs.com/package/git-snapshot
> 
> I want a simpler release workflow...
> 
> * Changelog: Generate based on commit message, not Github issues.
>   
>   * https://github.com/conventional-changelog/conventional-changelog
> * Versioning: Automatically, not manually
> * Portability: Just execute `npm run release`
> * Release: Tag and squashed-split to upm branch and release on Github

Thank you! That is exactly what I needed for this workflow.

The GitHub repo link for that npm package is broken though. 
https://github.com/mob-sakai/git-snapshot

**Comment by starikcetin** [comment]
Also you may want to include this git script in the readme, it really makes things easier.

**Comment by starikcetin** [comment]
Hey, just to let you know, I wrote a python application that automates the whole Git-repo-to-upm-package process: https://github.com/starikcetin/git-upm-publisher

It handles package.json creation, package.json updating, package.json search within repo, and publishing process using your git-snapshot command; along with a main script to do everything within a single script.

It is still a long way from being mature, but I am already using it to convert various amazing git repos to upm packages: https://github.com/starikcetin/awesome-upm

**Comment by mob-sakai** [comment]
Sorry my late reply.

git-upm-publisher is a good idea. :)
I am delighted to be able to release it on the command line.
Currently, I am working on automatic release support via [semantic-release](https://github.com/semantic-release/semantic-release).
It generates a changelog, publishes it to any npm registry (option), and updates the upm branch.

Aside from that, I came up with a way to install subdirectory packages.
It is not yet ready for release, but it may fulfill your wishes. :)
