### ISSUE TITLE
Does not support custom port for ssh

### ISSUE THREAD

**Issue by dimmduh** [mob-sakai/UpmGitExtension#47]
I use port 22100 and it works fine when fetching branches, but when I click install

ssh://git@my.gitlab.com:22100/npm/simple-packages.git

Error when executing git command. ssh: connect to host my.gitlab.com port **22**: Connection refused
  fatal: Could not read from remote repository.

**Comment by dimmduh** [comment]
I works if use https

**Comment by mob-sakai** [comment]
Hi @dimmduh 
I would like to know more information on this issue.

**Environment (please complete the following information):**
 - Platform: [e.g. Editor(Windows/Mac), Standalone(Windows/Mac)]
 - Unity: [e.g. 2018.3.0f1]
 - UpmGitExtension: [e.g. v0.9.1]

**Comment by dimmduh** [comment]
Windows 7 SP1
Unity 20191.10f1
v0.9.1

**Comment by mob-sakai** [comment]
@dimmduh 
Sorry for my late reply.

Is it possible to install the package manually, ie by editing `manifest.json` ?

**Comment by JurjenBiewenga** [comment]
This should be fixed in my PR #88
