### ISSUE TITLE
FindVersion button does not update version

### ISSUE THREAD

**Issue by dimmduh** [mob-sakai/UpmGitExtension#48]
Clicking FindVersion button does not not update version.
Maybe cache.

Steps
1) push package to repo
2) in another project open add git package window
3) enter repository url and click "find version"
4) understand that forget to add or push tag
5) push tag
6) click "find version" to update version dropdown
7) version dropdown is not updating

Windows 7 SP1
Unity 20191.10f1
v0.9.1
I'm using gitlab ce

**Comment by dimmduh** [comment]
Hmmm... after writing issue, I clicked button again and it updates
It seems to cache

**Comment by mob-sakai** [comment]
Ref: #62 
It will be fixed in the next version
