### ISSUE TITLE
Strange with version and update

### ISSUE THREAD

**Issue by dimmduh** [mob-sakai/UpmGitExtension#49]
![image](https://user-images.githubusercontent.com/446814/64225693-0b25da80-cf0f-11e9-87c6-46050570f0fd.png)
It show this library has update - but not.

Have no idea how it possible. Maybe after adding my package via your plugin.

Windows 7 SP1
Unity 20191.10f1
v0.9.1

**Comment by dimmduh** [comment]
![image](https://user-images.githubusercontent.com/446814/64225811-98692f00-cf0f-11e9-8c61-54f1c69789c8.png)

**Comment by mob-sakai** [comment]
Hi @dimmduh 
Thank you for your reporting!
it seems a bug.
