### ISSUE TITLE
Support 2019.3

### ISSUE THREAD

**Issue by Ramobo** [mob-sakai/UpmGitExtension#50]
Currently, in 2019.3, nothing in the package works and the following error occurs upon selecting any package:
```
Package manager extension failed with error: Object reference not set to an instance of an object
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```
If only they had a stack trace...

Although it does seem that this project has been abandoned.

**Comment by Ramobo** [comment]
It appears that the error is somewhere in `UpmGitExtension.InitializeUI`.

**Comment by Ramobo** [comment]
I traced the issue back to line 147:
```
// Document actions.
documentActions = new DocumentActions(root.Q("detailActions"));
```
I guess they renamed something.

**Comment by Ramobo** [comment]
I traced the issue to line 144:
```
root = UIUtils.GetRoot(this).Q("container");
```
`root` is null. I guess they renamed something.

**Comment by mob-sakai** [comment]
Hi @Ramobo 

Thank you for your reporting!

**Comment by Ramobo** [comment]
Well, unsurprisingly, in hindsight, it's not a rename: it's restructuring.

**Comment by mob-sakai** [comment]
As you said, I found some UIElement paths and APIs changed.

**Comment by mob-sakai** [comment]
Wow, a wide range of APIs have been changed...
What a hell!

**Comment by mob-sakai** [comment]
For now, the progress is around 60%.

**Comment by mob-sakai** [comment]
WIP

![2019 3](https://user-images.githubusercontent.com/12690315/66622716-ba975080-ec23-11e9-9fad-a9f0ca0d9dd0.gif)

**Comment by Ramobo** [comment]
> Wow, a wide range of APIs have been changed...
What a hell!

Well, they did completely overhaul the editor UI and UX.

**Comment by hs-cheon** [comment]
@mob-sakai any news on this?

**Comment by mob-sakai** [comment]
Hi @hs-cheon 

I am significantly modifying this plugin to support 2019.3.
If it goes smoothly, it will be released next week.
