### ISSUE TITLE
Add support for installing packages in repository subdirectories

### ISSUE THREAD

**Issue by Ramobo** [mob-sakai/UpmGitExtension#51]
e.g.
```JSON
{
  "dependencies": {
    "com.example.package": "https://github.com/example/package.git#1.0.0/Example Package/Packages/com.example.package"
  }
}
```
This is useful for developing a package in a project repository and not having to move the package to the root for release, especially for those bitten by the organization bug, like me.

**Comment by Ramobo** [comment]
Well, I found #46. The package manager does *not* feel ready at all to me.

**Comment by mob-sakai** [comment]
I came up with a way to install subdirectory packages.
It is not yet ready for release, but it may fulfill your wishes. :)
