### ISSUE TITLE
Reflection Error

### ISSUE THREAD

**Issue by m3rt32** [mob-sakai/UpmGitExtension#58]
**Describe the bug**
A reflection error occurs when I open up the package manager and package manager becomes uninteractable. Error is as follows:

> ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.

**To Reproduce**
1. Go to Package Manager
2. Just Open it up
3. Wait for a few seconds.
4. Check out the Debug Console.
Note, my "Show Preview Packages" were enabled before this package was installed.

**Expected behavior**
The Package Manager will freeze and error message will be thrown.

**Environment (please complete the following information):**
 - Version 1.0.2
 - Platform: All in editor
 - Unity version: 2019.2.9f1

**Comment by mob-sakai** [comment]
Hi @m3rt32 

Thank you for your reporting!
