### ISSUE TITLE
Not working if the user name or project path contains spaces

### ISSUE THREAD

**Issue by crmagicxxx** [mob-sakai/UpmGitExtension#68]
I tried from preview 1 to 4 and with latest 1.0.0 and I always get this error in Package Manager:

[Utils.ExecuteShell] failed: script = cmd.exe, args = /C *****\_Templates\2D Game Template\Library\PackageCache\com.coffee.upm-git-extension@e8338267b3fbbf5b8405b03c18ad2ec31a399f14\Editor\Commands\get-available-refs.bat https://github.com/mob-sakai/UpmGitExtension.git *****\AppData\Roaming\UpmGitExtension\com.coffee.upm-git-extension%40https%3A%2F%2Fgithub.com%2Fmob-sakai%2FUpmGitExtension.git 2019.2.13f1
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

And because of that, I can't see a list of other UPM versions

Thanks
Best

**Comment by mob-sakai** [comment]
Hi @crmagicxxx 
Thank you for your reporting!

Hmm, I think this is because the path contains spaces.
As a test, execute the following command on the command prompt.
(the command is added double quotes)

`cmd.exe /C "*****_Templates\2D Game Template\Library\PackageCache\com.coffee.upm-git-extension@e833826\Editor\Commands\get-available-refs.bat" https://github.com/mob-sakai/UpmGitExtension.git "*****\AppData\Roaming\UpmGitExtension\com.coffee.upm-git-extension%40https%3A%2F%2Fgithub.com%2Fmob-sakai%2FUpmGitExtension.git" 2019.2.13f1`

**Comment by mob-sakai** [comment]
I will fix it ASAP

**Comment by crmagicxxx** [comment]
Actually, I had to add double quote on both commands, plus quotes on the beginning and the end:

cmd.exe /C ""*****\_Templates\2D Game Template\Library\PackageCache\com.coffee.upm-git-extension@e8338267b3fbbf5b8405b03c18ad2ec31a399f14\Editor\Commands\get-available-refs.bat" https://github.com/mob-sakai/UpmGitExtension.git "*****\AppData\Roaming\UpmGitExtension\com.coffee.upm-git-extension%40https%3A%2F%2Fgithub.com%2Fmob-sakai%2FUpmGitExtension.git" 2019.2.13f1"

**Comment by mob-sakai** [comment]
Not fixed inough:

**Comment by mob-sakai** [comment]
It seems work well.

@crmagicxxx 
Does it work in your environment?

**Comment by crmagicxxx** [comment]
It doesn't show any errors now, but still doesn't display any other versions

**Comment by crmagicxxx** [comment]
I see one difference in manifest.json. Before under "lock" there was revision number, now it'sL
`"lock": {
    "com.coffee.upm-git-extension": {
      "hash": "*****",
      "revision": "HEAD"
    }
  }`

**Comment by mob-sakai** [comment]
Ah, please remove the "lock" element.

**Comment by mob-sakai** [comment]
Hmm, do you thnk that "unlock package revision" menu is convinient?

**Comment by crmagicxxx** [comment]
Yes, I completely removed UPM package and closed Unity. Everything got removed from manifest. Then I manually added UPM url and started Unity. “Lock” was added automatically
