### ISSUE TITLE
Support Bitbucket.org

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/UpmGitExtension#7]

**Comment by Babilinski** [comment]
Please please add support for this. You would become number 1 in my developer heart <3

**Comment by mob-sakai** [comment]
Hi @Babilinski 
I'm sorry to delay release.
Don't worry, I have finished my research on this feature.
This will be implemented soon. :)

**Comment by mob-sakai** [comment]
@Babilinski
ver.0.5.0 has been released!
