### ISSUE TITLE
Would you pls append this article into you Readme context?

### ISSUE THREAD

**Issue by Bian-Sh** [mob-sakai/UpmGitExtension#70]
雨落随风 - 简书
https://www.jianshu.com/u/275cca6e5f17

This is a translated version of your tutorial：
https://www.patreon.com/posts/25070968

I think someone may need it。

**Comment by mob-sakai** [comment]
Thank you for translating my article.
By the way, I plan to update the article.
- It's better to use `git snapshot` than `git subtree`
- Mechanism to support npm registry
- Develop under the Packages directory

Should I inform you of an article update?

**Comment by Bian-Sh** [comment]
Yeap ! Please let me know if you update the article, and everything you do is worth looking forward to.
