### ISSUE TITLE
A thousand github login windows

### ISSUE THREAD

**Issue by MeisterDerMagie** [mob-sakai/UpmGitExtension#71]
I just added UpmGitExtension to the package manifest.json and this happened:

I'm on Unity 2019.2.14f1

![grafik](https://user-images.githubusercontent.com/40137439/70432799-66bcb280-1a80-11ea-9d43-0d8f855e4963.png)

**Comment by mob-sakai** [comment]
Hi @MeisterDerMagie 

Thank you for your reporting!
Try to use `https://` protocol instead of `git:` or `git@` protocol.

**Comment by mob-sakai** [comment]
Find Packages/manifest.json in your project and edit it to look like this:

```js
{
  "dependencies": {
    "com.coffee.upm-git-extension": "https://github.com/mob-sakai/UpmGitExtension.git",
    ...
  },
}
```
