### ISSUE TITLE
Nothing happens ...

### ISSUE THREAD

**Issue by MeisterDerMagie** [mob-sakai/UpmGitExtension#73]
Hey, I have a third issue that stops me from using UpmGitExtension.
When I press "Find Versions" the package manager disables all fields but nothing happens, even after waiting for more than 10 minutes.
Tried this in Unity 2019.14f1 and 2019.15f1.

![grafik](https://user-images.githubusercontent.com/40137439/70444987-0f780b80-1a9b-11ea-8dcc-260dc1be6b1c.png)

**Comment by mob-sakai** [comment]
Hi @MeisterDerMagie 

Thank you for your reporting!

**Comment by Mathijs-Bakker** [comment]
Hi!

Just to append this to the issue:
<img width="746" alt="Schermafbeelding 2019-12-10 om 21 27 59" src="https://user-images.githubusercontent.com/7645831/70566235-f99a4180-1b93-11ea-9221-b96636496573.png">

Issue: **Package Manager Gets Unresponsive When ``Find Versions`` Button Is Clicked**

The Unity Package Manager is unresponsive (select url field and close button doesn't work). And the UPM Git Extension is blocking the whole UPM UI. The only way to reset is to close the UPM tab.

- Unity 2019.3
- MacOS 10.15.1
- Clean Unity project.
- With standard Packages and Package Validation Suite installed.

How to replicate:
1. Click Install Packages Git icon,
2. Paste git url
3. Hit ``Find Versions``

Maybe this gives some more context.

**Comment by robertocaldas** [comment]
Hi. I'm having the same issue with Unity 2019.2.8.
I manually added a package and it works, so it's not something with the package's repo/content.

I also noticed that the "Update to" button and preview of older versions don't work, even when I try seeing UpmGitExtension details.

Unity is changing the contents of manifest.json to a different structure of what's documented, I wonder if that's not breaking your code:

`    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  },
  "lock": {
    "com.rob.unity-package-test": {
      "hash": "e5b6667c0fc6ca048a9a2fb716eb3ac9241f144e",
      "revision": "HEAD"
    }
  }
}`

On another subject, it seems that your package.json and package.json.meta gets copied to my project's root folder (in the same level of Assets folder), do you know why this happens?

**Comment by mob-sakai** [comment]
@MeisterDerMagie @Mathijs-Bakker @robertocaldas 
Do you use UnityHub 2.2.x to launch UnityEditor?

It has a strange bug.
https://forum.unity.com/threads/unityhub-2-2-0-miss-git-executable.785288/#post-5231825 

Please try to launch UnityEditor without UnityHub.

**Comment by mob-sakai** [comment]
@MeisterDerMagie @Mathijs-Bakker @robertocaldas
Hey guys, UnityHub 2.2.2 has been released!

**Comment by tylo** [comment]
I'm having this same bug happen to me, and am using UnityHub 2.2.2

**Comment by mob-sakai** [comment]
@MeisterDerMagie @Mathijs-Bakker @robertocaldas @tylo 
Sorry, I will fix it.

**Comment by albermotion** [comment]
I'm having the same problem with Unity 2019.3.0f3 and Unity Hub 2.2.2.
It could be something related to 2019 version? I didn't have this problem with 2018.

**Comment by Zeterro** [comment]
Hey! Same here with Unity 2019.3.0f5 and Unity Hub 2.2.2 on Windows.
