### ISSUE TITLE
Git Package Version Selector not working

### ISSUE THREAD

**Issue by rafcsoares** [mob-sakai/UpmGitExtension#75]
Hello mob-sakai, thank you for this amazing package.

I'm using Unity 2019.3.0f1 and the version selector was not working on it (including in your packages like "Git Dependence Resolver")

![image](https://user-images.githubusercontent.com/45020302/71213737-1bca4880-2293-11ea-8cbe-15d90e1bb59f.png)

Thanks in advance
Rafael

**Comment by mob-sakai** [comment]
Hi @rafcsoares 

Thank you for your reporting.
If you are using UnityHub 2.2.1, upgrade to 2.2.2.

**Comment by rafcsoares** [comment]
yeah @mob-sakai, i already using version 2.2.2.

**Comment by mob-sakai** [comment]
Ref: #73
