### ISSUE TITLE
Currently Crashing 2020.1.0a18

### ISSUE THREAD

**Issue by evanricard** [mob-sakai/UpmGitExtension#76]
This is probably a known issue but I thought I would mention that 2020 is crashing when this reference gets added to packages.json...do I need to have a scoped registry or does it just crash because I'm using Unity 2020?

Thanks!

**Comment by mob-sakai** [comment]
Hi @evanricard ,

Unity 2020.x is not supported yet. (WIP)

**Comment by evanricard** [comment]
Thank you @mob-sakai

**Comment by Tr0sT** [comment]
Any plans to add support?

**Comment by mob-sakai** [comment]
@Tr0sT @evanricard 
Sorry for the delay in the update.
It's currently being tested on 2020.1.
