### ISSUE TITLE
Calling Application.unityVersion outside main thread

### ISSUE THREAD

**Issue by Slowlearneruk** [mob-sakai/UpmGitExtension#78]
If debugger is connected to player I am getting exceptions thrown in GitUtils.GetRefs as it is called outside of the main unity thread:

UnityEngine.UnityException: get_unityVersion can only be called from the main thread.

I think that it is being called recursively from the GitUtils.ExecuteShell on completion callback which is not guaranteed to be in the same thread it was launched from. 

Steps to reproduce the behaviour:
1. Connect debugger to Unity Player in Rider 2019.3
2. Open package manager
3. Wait

Version: 2.0.8
Platform: Editor
Unity version: 2018.4.15f1
Build options: NA

Not sure if there are any other calls that require the main thread but a good starting point is probably to cache the Unity version rather than keep sampling it.

**Comment by mob-sakai** [comment]
Hi @Slowlearneruk ,

Thank you for your reporting!

**Comment by mob-sakai** [comment]
@Slowlearneruk , please tell me the package version.

**Comment by Slowlearneruk** [comment]
2.0.8 - was in the bug report :)

**Comment by mob-sakai** [comment]
Currently, the latest version is `1.1.0-preview.6`.
https://github.com/mob-sakai/UpmGitExtension/releases

**Comment by Slowlearneruk** [comment]
oh.. checking again.. sorry (that was the Package Manager version) 1.0.1

**Comment by mob-sakai** [comment]
OK, `1.0.0` and `1.0.1` contain some bug.
Please try to use `1.1.0-preview.6`.

**Comment by Slowlearneruk** [comment]
Seems to have resolved the issue. Thanks.
