### ISSUE TITLE
Azure Dev Ops and Branch Support

### ISSUE THREAD

**Issue by TCROC** [mob-sakai/UpmGitExtension#80]
Would it be possible to add support for [Azure Dev Ops](https://azure.microsoft.com/en-us/services/devops/) in a private organization?  Maybe I'm just doing something wrong, but I could not seem to get it to work.

Also, can you add support for seeing different versions in a specific branch without having to set that branch as the default branch?

Both of these would make development A LOT easier within our studio.

**Comment by mob-sakai** [comment]
Hi @TCROC 

OK, I will try it.

> Also, can you add support for seeing different versions in a specific branch without having to set that branch as the default branch?

UpmGitExtension supports tags and branches that are not the default branch.

**Comment by TCROC** [comment]
Awesome! Can't wait! :)

**Comment by TCROC** [comment]
I decided to give it a stab and see what was up.  It looks like the asset is adding ".git" to the end of the Dev Ops git url.  It seems to pull it down now after I prevented it from adding that to the end of the url, but a history of versions still aren't appearing.

**Comment by mob-sakai** [comment]
@TCROC 

Thanks!

**Comment by TCROC** [comment]
Hey @mob-sakai Just checking in to see if you've found anything with this issue :).  I haven't had the chance to look into it any further yet.

**Comment by mob-sakai** [comment]
Hi @TCROC 

Sorry for the late reply.

I noticed that Unity 2018.x do not support Azure Dev Ops.
Unity 2019.x support it but `git+` is required as a prefix.
https://forum.unity.com/threads/package-manager-cant-clone-azure-dev-ops-repos.628948/

**Comment by TCROC** [comment]
Yes, that is correct.  We are using git+, but for some reason, your tool adds ".git" to the end of the URL.

**Comment by mob-sakai** [comment]
Exactly.
The tool explicitly adds a `.git` suffix, as Unity 2018.x does not support `git+` prefix.
So if the tool supports `git+` prefix, this issue will be solved. :)

**Comment by TCROC** [comment]
Ah I see!  Awesome! :)  I look forward to using it with the fix! :)

**Comment by mob-sakai** [comment]
Please try to use `v1.1.0-preview.11` :)

**Comment by TCROC** [comment]
Awesome!  I'll try it out tonight and let you know :)

**Comment by TCROC** [comment]
Hey sorry that it's taken me so long to get to this.  We've recently had things come up in development which we had to prioritize.  I will definitely test this before the end fo the week though.

**Comment by TCROC** [comment]
Ok so I got a chance to test it out.  It seems that it clones down, however I cannot select between any versions.

Another piece of information: We are using an LFS enabled repository.  Would that have anything to do with it?

**Comment by TCROC** [comment]
Also, does every commit in my UPM branch need to be formatted for UPM?  Would that prevent the tool from finding version?

**Comment by TCROC** [comment]
I tried setting my UPM branch as my default branch, but that didn't fix anything

**Comment by mob-sakai** [comment]
Hmm, it is strange...

**Comment by mob-sakai** [comment]
Do you use ssh url to clone?

Copy from here

![image](https://user-images.githubusercontent.com/12690315/75766152-08a02280-5d84-11ea-81b0-1eb804ec91d3.png)

...and paste to here?

![image](https://user-images.githubusercontent.com/12690315/75766267-38e7c100-5d84-11ea-8dcc-0ee88d2d3175.png)

**Comment by mob-sakai** [comment]
![image](https://user-images.githubusercontent.com/12690315/75767224-ca0b6780-5d85-11ea-9cec-20515a95c9a0.png)

**Comment by TCROC** [comment]
No, I did not use the SSH URL.  We are cloning vis HTTPS.

**Comment by mob-sakai** [comment]
To clone private repository,

## Solution 1: Use `ssh` protocol

See https://github.com/mob-sakai/UpmGitExtension/issues/80#issuecomment-593875502

## Solution 2: Use password to authenticate

`https://{username}:{password}@dev.azure.com/{organization}/{projectname}/_git/{projectname}`

**NOTE: This solution is not recommended for security reasons.**

**Comment by TCROC** [comment]
I don't use either of those when adding the git url directly to UPM

![image](https://user-images.githubusercontent.com/24307049/75804117-8268e980-5d4d-11ea-8f3a-5b0a3b0e90ff.png)

It simply prompts me for my user name and password once, caches it, then pulls everything down from my private repo.  No need for SSH or password.

**Comment by TCROC** [comment]
Upon testing it out again: it appears to clone my repo

![image](https://user-images.githubusercontent.com/24307049/75822376-dd123d80-5d6d-11ea-8596-085b39e74e8d.png)

It just doesn't give me any options for selectin any versions.  I am not specifying any branches in the clone url.  My default branch of master is not the upm branch.  Is that required for this to work?

It works using the default upm.  I just can't select different versions with the default upm which I why I'm trying to use this great tool 😃

**Comment by mob-sakai** [comment]
![image](https://user-images.githubusercontent.com/12690315/75844233-bceb8880-5e18-11ea-8020-1e6a23747bce.png)

**Comment by mob-sakai** [comment]
`upm` branch is not required.
UpmGitExtension checks `package.json` in root directory from all branches and tags.
Of those, only those packages that support the Unity version you are using are listed.

If the version is not displayed in the installation window, check the following:
- Are branches and tags set for each version?
- Does the package version support the Unity version you are using?

**Comment by TCROC** [comment]
I did click there.  It didn't give me any options.

> Are branches and tags set for each version?

What exactly do you mean by that?  I guess I thought that meant I had to format the structure of the files in the upm branch to support upm.  As in making sure packages.json is in the root directory, removing project settings folder, etc.  Maybe I am missing something though.  I'll post a screenshot of what my structure looks like when I get home.

> Does the package version support the Unity version you are using?

I did not set the Unity version in the package.  When leaving that unset, it by default supports all Unity Versions.  I'll try setting a Unity version and see if that fixes it.

> Please tell me the branch name.

I have 2 branches.

1. releases/upm
2. releases/upm-test

Both branches are in the form to support upm with package.json being in the root directory.

**Comment by TCROC** [comment]
![image](https://user-images.githubusercontent.com/24307049/75940307-abc36b80-5e5a-11ea-9642-b18ab936e0c2.png)

I had to create a tag for a release... my bad.  I can confirm that the preview release fixes the bug with pulling down Azure repos (including private repos).  It wasn't working for me because I didn't have tags created for the releases I wanted.  I've never worked with tags before so I was unaware of how they work.  Now I know 😄 Thanks for the fast response and fix.  This can now be marked as resolved.

**Comment by mob-sakai** [comment]
I noticed that the tool did not support nested branches...

- releases/upm
- releases/upm-test
