### ISSUE TITLE
Releases wrongly being flagged as "preview"

### ISSUE THREAD

**Issue by TCROC** [mob-sakai/UpmGitExtension#83]
![image](https://user-images.githubusercontent.com/24307049/76026676-42486900-5efd-11ea-9bdb-eb4bdf1b3a1d.png)

![image](https://user-images.githubusercontent.com/24307049/76026790-7754bb80-5efd-11ea-98b0-8def9b41480e.png)

package.json
```json
{
    "name": "com.somestudio.inventorysystem",
    "displayName": "Inventory System",
    "description": "This package contains the inventory system.",
    "version": "2.7.4",
    "author": "Some Studio",
    "url": "https://www.somestudio.com",
    "dependencies": {
        "com.unity.textmeshpro": "2.0.1"
    },
    "scripts": {
        "version": "echo $npm_package_version"
    },
    "type": "tool",
    "hideInEditor": false,
    "unity": "2017.1",
    "unityRelease": "0f1"
}
```

My releases in Azure Dev Ops private repo are being flagged as preview.  But only if I am not currently on that version.  If I  "Update To" the version, it no longer flags it as a preview build.

**Comment by TCROC** [comment]
The only difference between those 2 versions that are flagged as "preview" and the versions that aren't flagged as "preview" is the "Tag" matches the package.json version exactly.  The other ones were offset by 1 version due to a bug in our build pipeline.  We recently patched that bug and discovered this bug.

Example:

**Version 2.7.4**
Tag = 2.7.4
package.json version = 2.7.4

**Version 2.7.2**
Tag = 2.7.1
package.json version = 2.7.2

**Comment by TCROC** [comment]
![image](https://user-images.githubusercontent.com/24307049/76151989-9f245a80-6088-11ea-929c-0a10cdb83a06.png)

Ok so the versions that match the tags are no longer being flagged as preview.  However, everything else is not being flagged as preview.  What are the rules that determine if a release is flagged as preview?

**Comment by TCROC** [comment]
![image](https://user-images.githubusercontent.com/24307049/76152034-1528c180-6089-11ea-97c9-717eeb3b74bd.png)


Ok so the versions that match the tags are no longer being flagged as preview. However, everything else is now being flagged as preview. What are the rules that determine if a release is flagged as preview?

**Comment by mob-sakai** [comment]
Sorry for the late reply.
If the version and the branch/tag name are different, it seems to be considered a preview.

**Comment by TCROC** [comment]
> Sorry for the late reply.

No problem :)

> If the version and the branch/tag name are different, it seems to be considered a preview.

Is this an intended feature?  If so, I'll close this issue.  Otherwise I'll leave it open.
