### ISSUE TITLE
how to reenter credentials if i entered wrongly the first time

### ISSUE THREAD

**Issue by fight4dream** [mob-sakai/UpmGitExtension#86]
![image](https://user-images.githubusercontent.com/22952143/76897463-c243db00-68ce-11ea-8b45-5095705e1b7d.png)

after i entered the repo url and failed to enter correct credentials, it doesn't prompt me again to reenter the correct one. how to clear the 'existing incorrect credential' ?

**Comment by TCROC** [comment]
If you are on windows I recommend using [Git Credential Manager](https://github.com/microsoft/Git-Credential-Manager-for-Windows).  If you are on Mac I recommend using [Git Credential Manager Core](https://github.com/microsoft/Git-Credential-Manager-Core).

**Comment by TCROC** [comment]
The work seamlessly with any git interface including this repo.

**Comment by TCROC** [comment]
@mob-sakai  I think we can probably close this issue
