### ISSUE TITLE
Unity Cloud Build fails with SSH URL

### ISSUE THREAD

**Issue by brogan89** [mob-sakai/UpmGitExtension#87]
**Describe the bug**
Unity Cloud Build fails when installing git URL through your method. It is fine when done normal Unity Package Manager way. 

I am using ssh rather than https and I think that is related. 
The URL that your plugin returns is `ssh://git@{repo}.git#master` but Unity generates `git@{repo}.git`

The error that UCB gives is
```
113: [Unity] Using Asset Import Pipeline V2.
114: [Unity] DisplayProgressbar: Unity Package Manager
115: [Unity] Rebuilding Library because the metadata folder could not be found!
116: [Unity] Adding genesis user token Error when executing git command:
117: [Unity]   - stdout: 
118: [Unity] git@gitlab.com: Permission denied (publickey).
119: [Unity] fatal: Could not read from remote repository.
120: [Unity] Please make sure you have the correct access rights
121: [Unity] and the repository exists.
122: [Unity] [Package Manager] Done resolving packages in 2.50s seconds
123: [Unity] An error occurred while resolving packages:
124: [Unity]   Project has invalid dependencies:
125: [Unity]     git@gitlab.com: Permission denied (publickey).
126: [Unity]     fatal: Could not read from remote repository.
127: [Unity]     Please make sure you have the correct access rights
128: [Unity]     and the repository exists.
129: [Unity] A re-import of the project may be required to fix the issue or a manual modification of /BUILD_PATH/blackout-sports.rugby.win64-nightly/Packages/manifest.json file.
130:        ! Unity player export failed!
131: ! build of 'win64-nightly' failed. exit
132: Publishing build 94 of blackout-sports/rugby for target 'win64-nightly'...
133: publishing finished successfully.
134: Zipping cache files from Library
135: done.
136: Build step 'Execute shell' marked build as failure
137: Using /BUILD_PATH/.rvm/gems/ruby-2.4.2
138: postbuildstatus finished successfully.
139: postbuildsteps finished successfully
140: Finished: FAILURE
```

**To Reproduce**
1. Install a private repo with ssh URL 
2. Run Unity Cloud Build (any platform)
3. Build should fail with similar message above.

**Expected behavior**
The build to work. 

**Environment (please complete the following information):**
 - Version `preview.12-1.1.0`
 - Platform: Windows
 - Unity version: 2019.3.5f1
 - Build options: IL2CPP, .Net 4.x, URP

**Additional context**
There is also a difference in the way this package handles the `lock` instead of `"revision": "HEAD"` its `revision: "master"` but I don't think that has anything to do with the issue. It's something to do with the way the URL is handled.

Let me know if I'm missing something too, it should be something I have over looked.

**Comment by mob-sakai** [comment]
@brogan89 
If the project opens fine locally, I'm afraid this sounds like a Cloud Build specific issue.
You might have better luck asking in https://forum.unity.com/forums/unity-cloud-build.61/
