### ISSUE TITLE
Windows defender reporting OpenSesame compilers as a Trojan

### ISSUE THREAD

**Issue by albertogr91** [mob-sakai/UpmGitExtension#91]
**Describe the bug**
While updating to version 1.1.0 a Windows Defender notification popped-up. Installation fails as files get quarentined.

**To Reproduce**
1. Update to version 1.1.0
2. Have Windows Defender activated

**Screenshots**
![error](https://puu.sh/GgFMe/647860de9a.png)
![trojan](https://puu.sh/GgFPe/25a6302c8c.png)
![affectedline](https://puu.sh/GgFQ8/4fc6904d44.png)

**Environment:**
 - Version 1.1.0
 - Platform: Windows
 - Unity version: 2019.3.9f1

**Comment by mob-sakai** [comment]
@albertogr91 
Thank you for your reporting!
The issue is reproduced on my PC.
I didn't notice it because I was using a different anti-virus software.

**Comment by mob-sakai** [comment]
On windows, we can get around this by changing the download tool for the nuget package.
I will fix it ASAP.

**Before: ** `certutil.exe`
**After: ** `powershell.exe curl`

**Comment by albertogr91** [comment]
Thank you @mob-sakai!
