### ISSUE TITLE
Currently crushing 2020.2.0a19

### ISSUE THREAD

**Issue by Tr0sT** [mob-sakai/UpmGitExtension#92]
After added this package using git via package manager
[Screenshot](https://gyazo.com/63fff10fdbabf5dae1ee64c247269988)

**Comment by mob-sakai** [comment]
@Tr0sT 
Please try `v1.2.3`.

**Comment by Tr0sT** [comment]
Library\PackageCache\com.coffee.upm-git-extension@b161ec9d03\Editor\Coffee.UpmGitExtension\InternalBridge.cs(135,25): error CS0117: 'PageManager' does not contain a definition for 'instance'

**Comment by mob-sakai** [comment]
Sorry, I mistakenly thought it was version 2020.1.
I will fix it later.
