### ISSUE TITLE
Unity 2020.1.5 & 2019.4.10 report an error

### ISSUE THREAD

**Issue by crmagicxxx** [mob-sakai/UpmGitExtension#97]
Library\PackageCache\com.coffee.upm-git-extension@ecf4c7d1b0\Editor\Coffee.UpmGitExtension\InternalBridge.cs(210,25): error CS7036: There is no argument given that corresponds to the required formal parameter 'isUnityPackage' of 'UpmPackageVersion.UpmPackageVersion(PackageInfo, bool, SemVersion?, string, bool)'

**Comment by mob-sakai** [comment]
@crmagicxxx 
Thank you for your reporting!

**Comment by Tr0sT** [comment]
Same on 2020.2.0b2

**Comment by mob-sakai** [comment]
@Tr0sT 
Thank you for your reporting!
