### ISSUE TITLE
Custom compiler installation failed.

### ISSUE THREAD

**Issue by fromkms** [mob-sakai/UpmGitExtension#98]
Hello mob-sakai! Trying to install your package through Unity Package Manager and get this error. What should i do next?

![error1](https://user-images.githubusercontent.com/9380200/93010335-cecf9480-f5ce-11ea-947f-28ea891ccea7.jpg)
![error2](https://user-images.githubusercontent.com/9380200/93010336-cf682b00-f5ce-11ea-9943-5f0dc2328ff4.jpg)
![error3](https://user-images.githubusercontent.com/9380200/93010337-d0995800-f5ce-11ea-826c-be6ec3f9ba3a.jpg)
![error4](https://user-images.githubusercontent.com/9380200/93010338-d131ee80-f5ce-11ea-91e7-59b456f0cce5.jpg)

I'm using unity 2019.4.9f1
Windows 10 ver 1803

**Comment by mob-sakai** [comment]
Hi @fromkms ,
thank you for your reporting.
It seems a bug and I will fix it ASAP.

**Comment by mob-sakai** [comment]
@fromkms 
By the way, can I run the following commands with command prompt?
`PowerShell.exe curl -O Temp\tmp59d90e97.tmp https://globalcdn.nuget.org/packages/OpenSesame.Net.Compilers.3.4.0.nuget`

Or,

`PowerShell.exe [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; curl -O Temp\tmp59d90e97.tmp https://globalcdn.nuget.org/packages/OpenSesame.Net.Compilers.3.4.0.nuget`

**Comment by mob-sakai** [comment]
@fromkms 
Please try to use `v1.3.3`.

By the way, can I run the following commands with command prompt?
`PowerShell.exe "curl https://globalcdn.nuget.org/packages/opensesame.net.compilers.3.4.0.nupkg"`

Or,

`PowerShell.exe "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; curl  https://globalcdn.nuget.org/packages/opensesame.net.compilers.3.4.0.nupkg"`

EDIT: The command is fixed.

**Comment by fromkms** [comment]
@mob-sakai 
Latest patch was installed correctly, thank you very much!

First command seems to be working, but second returns "Syntax error in file name, folder name or volume name"

**Comment by mob-sakai** [comment]
@fromkms 
Thank you for your cooperation!

**Comment by fromkms** [comment]
It seems i run commands incorrectly, here is another try.

First: Request was interrupted: Can't create secure SSL/TLS channel

Second: The content of the response cannot be parsed because the Internet Explorer subsystem is not available or because the configuration is incomplete when Internet Explorer is first started. Specify the UseBasicParsing parameter and try again.

**Comment by mob-sakai** [comment]
@fromkms 
Thanks!
Can you run the following command on **PowerShell**?
‘[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; curl -O test.zip https://globalcdn.nuget.org/packages/opensesame.net.compilers.3.4.0.nupkg’

**Comment by fromkms** [comment]
@mob-sakai 
It works perfectly!
As a result i get test.zip file in my folder.

**Comment by mob-sakai** [comment]
Thanks again, @fromkms !
