### ISSUE TITLE
Branches with _ in the name is not displayed in Unity UI for "more versions" in 2019.4.10f1

### ISSUE THREAD

**Issue by itayo** [mob-sakai/UpmGitExtension#99]
NOTE: Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

**Describe the bug**
Unable to see branches having a _ in the branch name
The specific character will not show the selected branch, the separator "-" in branchnames work but our working principle is 
JIRA-ISSUE_TITLE and these branches are not visible

**To Reproduce**
1. Create a branch named TEST-TEST_TEST in the external plugin repo
2. look at "more versions" in unity
3. Branch doesn't appear

**Expected behavior**
Branch named "TEST-TEST_TEST" is visible as a selectable version

**Environment (please complete the following information):**
 - Version 1.3.3
 - Platform:Editor(Windows & Linux)
 - Unity version: 2019.4.10f1
 - Build options: IL2CPP, .Net 4.x, LWRP

**Comment by itayo** [comment]
*debug: Looking at the output from the node script that fetches and creates a json file, the refNames are there.

**Comment by clarkxdy** [comment]
I'm using 2019.4.
The newest version didn't work at all.
So I tried to install some older versions, and v1.2.3 works fine so far.

**Comment by mob-sakai** [comment]
Since there has been no new discussion for a long time, this issue was closed.
 If the same issue arises, please re-open this issue.
